# Funding configuration
# Add your funding links here if you want to accept sponsorships

# github: yourusername
# patreon: yourusername
# ko_fi: yourusername
# custom: ["https://your-website.com/donate"]

