name: Deploy Backend to Railway

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'server/**'
      - 'Dockerfile'
      - 'railway.json'
      - 'package.json'
      - '.github/workflows/deploy-backend.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'server/**'

jobs:
  lint-and-test:
    name: Lint and Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check server code
        run: |
          echo "Checking server files..."
          node -c server/index.js

      - name: Test Docker build
        run: |
          docker build -t rapid-launch-backend:test .
          echo "Docker build successful"

  deploy:
    name: Deploy to Railway
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service=${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Health Check
        run: |
          sleep 30
          curl -f ${{ secrets.RAILWAY_URL }}/api/health || exit 1

